version: '3'

services:
  db:
    build: Db
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: Y
      #MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
